model:
  use_cuda: true
  compression_ratio: 0.5
  input_dim: 32
  num_layers: 4
  use_positional_encoding: true
  positional_multires: 50
  no_channels: 1
training:
  batch_size: 8
  learning_rate: 0.001
  num_epochs: 10
  eval_interval: 50

data:
  dataset_path: "data/esc50/audio"
  sample_rate: 22050
  transform:
    softmax: false
    min_max: true